spring:
    data:
      mongodb:
        database: gilded-rose
        uri: mongodb://localhost:27017
        
gilded-rose:
# number (from 0 to 23)
    update_quality_at_hour: "23"
# number (from 0 to 59)
    update_quality_at_minute: "0"
